    - name: Package OpenWrt Firmware
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
        PACKAGE_SOC: all
        KERNEL_VERSION_NAME: 5.15.95_6.1.15
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
